/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library.management.system.View;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import library.management.system.db.DBConnection;
import net.proteanit.sql.DbUtils;
public class Borrowing extends javax.swing.JFrame {

    Connection connection=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    public Borrowing() {
        initComponents();
         connection=DBConnection.connect();
         tableload();
    }
    public void tableload(){
        try {
            String sql="SELECT id AS ID,book_id AS BookID,member_id AS MemberID,borrow_date AS BorrowDate,return_date AS ReturnDate,due_date AS DueDate,fine AS Fine_APPLY FROM borrowings ";
            pst=connection.prepareStatement(sql);
            rs=pst.executeQuery();
            borrowingtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void tabledata(){
        int r=borrowingtable.getSelectedRow();
        String BorrowingID=borrowingtable.getValueAt(r,0).toString();
        String BookID=borrowingtable.getValueAt(r,1).toString();
        String MemberID=borrowingtable.getValueAt(r,2).toString();
        String BorrowDate=borrowingtable.getValueAt(r,3).toString();
        String DueDate=borrowingtable.getValueAt(r,4).toString();
        String ReturnDate=borrowingtable.getValueAt(r,5).toString();
        String Fine=borrowingtable.getValueAt(r,6).toString();
        
        borrowingidtxt.setText(BorrowingID);
        bookidtxt.setText(BookID);
        memberidtxt.setText(MemberID);
        borrowdatetxt.setText(BorrowDate);
        duedatetxt.setText(DueDate);
        returndatetxt.setText(ReturnDate);
        finetxt.setText(Fine);
    }

    
    public void update(){
        String Rid=borrowingidtxt.getText();
        String Bid=bookidtxt.getText();
        String Mid=memberidtxt.getText();
        String Bdate=borrowdatetxt.getText();
        String Ddate=duedatetxt.getText();
        String Rdate=returndatetxt.getText();
        String Fine=finetxt.getText();
        
        
        try {
            String sql="UPDATE borrowings SET id='"+Rid+"',book_id ='"+Bid+"',member_id= '"+Mid+"',borrow_date='"+Bdate+"',due_date='"+Ddate+"',return_date='"+Rdate+"',fine='"+Fine+"'WHERE id='"+Rid+"'";
            pst=connection.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Succsesfully Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    public void clear(){
        borrowingidtxt.setText("");
        bookidtxt.setText("");
        memberidtxt.setText("");
        borrowdatetxt.setText("");
        duedatetxt.setText("");
        returndatetxt.setText("");
        finetxt.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookidlbl = new javax.swing.JLabel();
        borrowingidtxt = new javax.swing.JTextField();
        borrowingidlbl = new javax.swing.JLabel();
        memberidlbl = new javax.swing.JLabel();
        borrowdatelbl = new javax.swing.JLabel();
        duedatelbl = new javax.swing.JLabel();
        returndatelbl = new javax.swing.JLabel();
        finelbl = new javax.swing.JLabel();
        bookidtxt = new javax.swing.JTextField();
        memberidtxt = new javax.swing.JTextField();
        borrowdatetxt = new javax.swing.JTextField();
        duedatetxt = new javax.swing.JTextField();
        returndatetxt = new javax.swing.JTextField();
        finetxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        borrowingtable = new javax.swing.JTable();
        bupdatebtn = new javax.swing.JButton();
        bclearbtn = new javax.swing.JButton();
        binsertbtn = new javax.swing.JButton();
        bdeletebtn = new javax.swing.JButton();
        bexitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("BORROWINGS");

        bookidlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookidlbl.setText("Book ID");

        borrowingidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowingidtxtActionPerformed(evt);
            }
        });

        borrowingidlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        borrowingidlbl.setText("Borrowing ID");

        memberidlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        memberidlbl.setText("Member ID");

        borrowdatelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        borrowdatelbl.setText("Borrow Date");

        duedatelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duedatelbl.setText("Due Date");

        returndatelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        returndatelbl.setText("Return Date");

        finelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finelbl.setText("Fine Apply");

        borrowingtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Borrowing ID", "Book ID", "Member ID", "Borrow Date", "Due Date", "Return Date", "Fine Apply"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        borrowingtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowingtableMouseClicked(evt);
            }
        });
        borrowingtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                borrowingtableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(borrowingtable);

        bupdatebtn.setText("Update");
        bupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdatebtnActionPerformed(evt);
            }
        });

        bclearbtn.setText("Clear");
        bclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearbtnActionPerformed(evt);
            }
        });

        binsertbtn.setText("Insert");
        binsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binsertbtnActionPerformed(evt);
            }
        });

        bdeletebtn.setText("Delete");
        bdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeletebtnActionPerformed(evt);
            }
        });

        bexitbtn.setText("Exit");
        bexitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(bexitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(borrowingidlbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(borrowingidtxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(finelbl)
                                        .addGap(38, 38, 38)
                                        .addComponent(finetxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bookidlbl)
                                        .addGap(62, 62, 62)
                                        .addComponent(bookidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(memberidlbl)
                                        .addGap(32, 32, 32)
                                        .addComponent(memberidtxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(borrowdatelbl)
                                        .addGap(23, 23, 23)
                                        .addComponent(borrowdatetxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(duedatelbl)
                                        .addGap(48, 48, 48)
                                        .addComponent(duedatetxt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(returndatelbl)
                                        .addGap(26, 26, 26)
                                        .addComponent(returndatetxt))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bclearbtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bdeletebtn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(binsertbtn)
                                    .addGap(90, 90, 90)
                                    .addComponent(bupdatebtn))))))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowingidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowingidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberidlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowdatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duedatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duedatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returndatelbl)
                    .addComponent(returndatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bupdatebtn)
                    .addComponent(binsertbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bclearbtn)
                    .addComponent(bdeletebtn))
                .addGap(18, 18, 18)
                .addComponent(bexitbtn)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(937, 567));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void borrowingidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowingidtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrowingidtxtActionPerformed

    private void binsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binsertbtnActionPerformed
       String BorrowingID;
       String BookID;
       String MemberID;
       String BorrowDate;
       String ReturnDate;
       String DueDate;
       String Fine;
       
       BorrowingID=borrowingidtxt.getText();
       BookID=bookidtxt.getText();
       MemberID=memberidtxt.getText();
       BorrowDate=borrowdatetxt.getText();
       ReturnDate=returndatetxt.getText();
       DueDate=duedatetxt.getText();
       Fine=finetxt.getText();
       
        try {
            String sql="INSERT INTO borrowings (id,book_id,member_id,borrow_date,return_date,due_date,fine) VALUES ('"+BorrowingID+"','"+BookID+"','"+MemberID+"','"+BorrowDate+"','"+ReturnDate+"','"+DueDate+"','"+Fine+"')";
            pst=connection.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "SUCCESSFULLY INSERTED");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        tableload();
    }//GEN-LAST:event_binsertbtnActionPerformed

    private void borrowingtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowingtableMouseClicked
         tabledata();
    }//GEN-LAST:event_borrowingtableMouseClicked

    private void borrowingtableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_borrowingtableKeyReleased
 tabledata();        // TODO add your handling code here:
    }//GEN-LAST:event_borrowingtableKeyReleased

    private void bupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdatebtnActionPerformed
update();
tableload();// TODO add your handling code here:
    }//GEN-LAST:event_bupdatebtnActionPerformed

    private void bdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeletebtnActionPerformed
       int check=JOptionPane.showConfirmDialog(null,"Do you want to delete");
if(check==0){
    String id=borrowingidtxt.getText();
    try {
        String sql="DELETE FROM borrowings WHERE id='"+id+"'";
        pst=connection.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null,"Deleted Successfully");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

}
tableload();
clear();
    }//GEN-LAST:event_bdeletebtnActionPerformed

    private void bclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearbtnActionPerformed
        clear();
    }//GEN-LAST:event_bclearbtnActionPerformed

    private void bexitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitbtnActionPerformed
  System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bexitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrowing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrowing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclearbtn;
    private javax.swing.JButton bdeletebtn;
    private javax.swing.JButton bexitbtn;
    private javax.swing.JButton binsertbtn;
    private javax.swing.JLabel bookidlbl;
    private javax.swing.JTextField bookidtxt;
    private javax.swing.JLabel borrowdatelbl;
    private javax.swing.JTextField borrowdatetxt;
    private javax.swing.JLabel borrowingidlbl;
    private javax.swing.JTextField borrowingidtxt;
    private javax.swing.JTable borrowingtable;
    private javax.swing.JButton bupdatebtn;
    private javax.swing.JLabel duedatelbl;
    private javax.swing.JTextField duedatetxt;
    private javax.swing.JLabel finelbl;
    private javax.swing.JTextField finetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel memberidlbl;
    private javax.swing.JTextField memberidtxt;
    private javax.swing.JLabel returndatelbl;
    private javax.swing.JTextField returndatetxt;
    // End of variables declaration//GEN-END:variables
}
