/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library.management.system.View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import library.management.system.db.DBConnection;
/**
 *
 * @author acer
 */
public class Customers extends javax.swing.JFrame {
 
   Connection connection=null;
   PreparedStatement pst= null;
    public Customers() {
        initComponents();
        connection=DBConnection.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerlbl = new javax.swing.JLabel();
        customernamelbl = new javax.swing.JLabel();
        contactnumberlbl = new javax.swing.JLabel();
        customeridlbl = new javax.swing.JLabel();
        customernametxt = new javax.swing.JTextField();
        customeridtxt = new javax.swing.JTextField();
        contactnumbertxt = new javax.swing.JTextField();
        minsertbtn = new javax.swing.JButton();
        mcancelbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerlbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        customerlbl.setText("MEMBERS");

        customernamelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customernamelbl.setText("Customer Name");

        contactnumberlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactnumberlbl.setText("Contact Number");

        customeridlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customeridlbl.setText("Member ID");

        customeridtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridtxtActionPerformed(evt);
            }
        });

        minsertbtn.setText("Insert");
        minsertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minsertbtnActionPerformed(evt);
            }
        });

        mcancelbtn.setText("Cancel");
        mcancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(contactnumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customernamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customeridlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(customeridtxt)
                                    .addComponent(customernametxt)
                                    .addComponent(contactnumbertxt, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mcancelbtn)
                        .addGap(41, 41, 41)))
                .addComponent(minsertbtn)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(customerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customeridlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customeridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customernamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(customernametxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contactnumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(contactnumbertxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minsertbtn)
                    .addComponent(mcancelbtn))
                .addGap(43, 43, 43))
        );

        setSize(new java.awt.Dimension(557, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customeridtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridtxtActionPerformed

    private void minsertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minsertbtnActionPerformed
         String CustomerID;
         String CustomerName;
         String ContactNumber;
         
         CustomerID=customeridtxt.getText();
         CustomerName=customernametxt.getText();
         ContactNumber=contactnumbertxt.getText();
         
         JOptionPane.showMessageDialog(null,"SUCESSFULLY INSERTED");
          try {
            String sql="INSERT INTO customers (id,name,contact_info ) VALUES ('"+CustomerID+"','"+CustomerName+"','"+ContactNumber+"')";
         pst=connection.prepareStatement(sql);
         pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
          Category c1=new Category();
        c1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_minsertbtnActionPerformed

    private void mcancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcancelbtnActionPerformed
   System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_mcancelbtnActionPerformed

     public static void main(String args[]) {
          java.awt.EventQueue.invokeLater(new Runnable() {
              public void run() {
                new Customers().setVisible(true);
            }
        });
     }
          
     
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactnumberlbl;
    private javax.swing.JTextField contactnumbertxt;
    private javax.swing.JLabel customeridlbl;
    private javax.swing.JTextField customeridtxt;
    private javax.swing.JLabel customerlbl;
    private javax.swing.JLabel customernamelbl;
    private javax.swing.JTextField customernametxt;
    private javax.swing.JButton mcancelbtn;
    private javax.swing.JButton minsertbtn;
    // End of variables declaration//GEN-END:variables
}
